version: "3"

services:
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - feedr

networks:
  feedr:
    name: feedr

volumes:
  redis:
    driver: local
